[package]
name = "dnstrace"
version = "0.1.0"
authors = ["David Jonas <djonas@noip.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = "2.32.0"
futures = "0.1.25"
rand = "0.5.5"
tokio = "0.1.11"
trust-dns = "0.15"
trust-dns-proto = "0.5.0"

[[bin]]
name = "dnstrace"
path = "src/main.rs"
